// Static seed data for demo / development
// In production this comes from the database

export const PET_TYPES = [
  { id: 'dog',     label: 'Dog',     emoji: '🐕', color: 'bg-amber-100 text-amber-800' },
  { id: 'cat',     label: 'Cat',     emoji: '🐈', color: 'bg-purple-100 text-purple-800' },
  { id: 'bird',    label: 'Bird',    emoji: '🐦', color: 'bg-sky-100 text-sky-800' },
  { id: 'rabbit',  label: 'Rabbit',  emoji: '🐇', color: 'bg-pink-100 text-pink-800' },
  { id: 'fish',    label: 'Fish',    emoji: '🐟', color: 'bg-blue-100 text-blue-800' },
  { id: 'reptile', label: 'Reptile', emoji: '🦎', color: 'bg-green-100 text-green-800' },
]

export const CERT_LEVELS = [
  {
    id: 'basic',
    label: 'Basic',
    description: 'Essential pet care fundamentals. Perfect for first-time owners.',
    price: 0,
    badge: 'Free',
    color: 'brand',
    perks: ['Digital certificate', 'Basic care guides', 'Community access'],
  },
  {
    id: 'standard',
    label: 'Standard',
    description: 'Deeper knowledge including nutrition, grooming, and health checks.',
    price: 29,
    badge: 'Most Popular',
    color: 'blue',
    perks: ['Everything in Basic', 'Breed-specific modules', 'Vet Q&A sessions', 'PDF certificate'],
  },
  {
    id: 'professional',
    label: 'Professional',
    description: 'Advanced care, first aid, emergency response and behavioural training.',
    price: 79,
    badge: 'Best Value',
    color: 'purple',
    perks: ['Everything in Standard', 'Pet first aid module', 'Behaviour & training', 'Printed certificate', 'Badge for social media'],
  },
  {
    id: 'expert',
    label: 'Expert',
    description: 'Multi-pet households, special needs, and senior pet care.',
    price: 149,
    badge: 'Pro',
    color: 'accent',
    perks: ['Everything in Professional', 'Multi-pet management', 'Special needs care', 'Lifetime access', 'Expert community'],
  },
]

export const SAMPLE_COURSES = [
  {
    id: '1',
    slug: 'dog-care-basics',
    title: 'Dog Care Fundamentals',
    description: 'Everything a first-time dog owner needs to know — feeding, exercise, grooming, and vet visits.',
    petType: 'dog',
    level: 'basic',
    price: 0,
    duration: 120,
    imageUrl: '/images/dog-basic.jpg',
    rating: 4.8,
    students: 3420,
    modules: 5,
    published: true,
  },
  {
    id: '2',
    slug: 'cat-care-standard',
    title: 'Complete Cat Care',
    description: 'Nutrition, indoor enrichment, grooming, health monitoring, and understanding cat behaviour.',
    petType: 'cat',
    level: 'standard',
    price: 29,
    duration: 180,
    imageUrl: '/images/cat-standard.jpg',
    rating: 4.9,
    students: 2108,
    modules: 7,
    published: true,
  },
  {
    id: '3',
    slug: 'dog-first-aid-pro',
    title: 'Dog First Aid & Emergency Care',
    description: 'CPR for dogs, choking, poisoning, wound care, and when to rush to the vet.',
    petType: 'dog',
    level: 'professional',
    price: 79,
    duration: 240,
    imageUrl: '/images/dog-pro.jpg',
    rating: 4.9,
    students: 987,
    modules: 9,
    published: true,
  },
  {
    id: '4',
    slug: 'bird-care-basics',
    title: 'Bird Owner Basics',
    description: 'Housing, diet, socialisation, and health signs for parrots, canaries and budgies.',
    petType: 'bird',
    level: 'basic',
    price: 0,
    duration: 90,
    imageUrl: '/images/bird-basic.jpg',
    rating: 4.7,
    students: 1203,
    modules: 4,
    published: true,
  },
  {
    id: '5',
    slug: 'rabbit-care-standard',
    title: 'Rabbit Care & Welfare',
    description: 'Housing, diet, dental care, and socialisation for happy, healthy rabbits.',
    petType: 'rabbit',
    level: 'standard',
    price: 29,
    duration: 150,
    imageUrl: '/images/rabbit-standard.jpg',
    rating: 4.8,
    students: 780,
    modules: 6,
    published: true,
  },
  {
    id: '6',
    slug: 'multi-pet-expert',
    title: 'Multi-Pet Household Management',
    description: 'Managing dogs, cats, and small animals together — introductions, feeding, and space management.',
    petType: 'general',
    level: 'expert',
    price: 149,
    duration: 300,
    imageUrl: '/images/multi-pet-expert.jpg',
    rating: 4.9,
    students: 445,
    modules: 12,
    published: true,
  },
]

export const SAMPLE_MODULES = [
  {
    id: 'm1',
    courseId: '1',
    title: 'Welcome & Setting Up Your Home',
    description: 'Preparing your home before your dog arrives.',
    order: 1,
    lessons: [
      { id: 'l1', title: 'Dog-proofing your space', duration: 8, content: 'Before your new dog arrives...' },
      { id: 'l2', title: 'Essential supplies checklist', duration: 6, content: 'What you need to buy...' },
      { id: 'l3', title: 'Setting up sleeping areas', duration: 5, content: 'Where should your dog sleep...' },
    ],
    quiz: {
      id: 'q1',
      passMark: 70,
      questions: [
        {
          id: 'qq1',
          text: 'Which of these should you do before bringing a new dog home?',
          options: ['Buy food only', 'Dog-proof your space and buy essentials', 'Nothing special needed', 'Wait until the dog arrives'],
          correctIndex: 1,
          explanation: 'Preparing your home in advance reduces stress for both you and your new pet.',
        },
        {
          id: 'qq2',
          text: 'Where is the best place for a dog to sleep?',
          options: ['Outside', 'In a designated comfortable bed/crate', 'On the kitchen floor', 'Anywhere they choose'],
          correctIndex: 1,
          explanation: 'A designated sleeping area gives dogs a sense of security.',
        },
        {
          id: 'qq3',
          text: 'What is the most important item to have before a dog arrives?',
          options: ['Toys', 'Food and water bowls', 'A collar with ID tag', 'A GPS tracker'],
          correctIndex: 2,
          explanation: 'An ID tag ensures your dog can be returned if lost.',
        },
      ],
    },
  },
  {
    id: 'm2',
    courseId: '1',
    title: 'Nutrition & Feeding',
    description: 'Understanding what your dog should eat and when.',
    order: 2,
    lessons: [
      { id: 'l4', title: 'Types of dog food', duration: 10, content: 'Dry, wet, raw — what is the difference...' },
      { id: 'l5', title: 'Feeding schedules by age', duration: 8, content: 'Puppies need to eat more frequently...' },
      { id: 'l6', title: 'Foods to avoid', duration: 7, content: 'Chocolate, grapes, onions are toxic...' },
    ],
    quiz: {
      id: 'q2',
      passMark: 70,
      questions: [
        {
          id: 'qq4',
          text: 'Which food is toxic to dogs?',
          options: ['Rice', 'Chicken', 'Chocolate', 'Carrots'],
          correctIndex: 2,
          explanation: 'Chocolate contains theobromine which is toxic to dogs.',
        },
        {
          id: 'qq5',
          text: 'How often should a 3-month-old puppy eat?',
          options: ['Once a day', 'Twice a day', '3-4 times a day', 'Free feeding all day'],
          correctIndex: 2,
          explanation: 'Young puppies need frequent meals to support their growth.',
        },
      ],
    },
  },
]

export const TESTIMONIALS = [
  {
    name: 'Sarah K.',
    role: 'First-time dog owner',
    text: 'PawCert gave me the confidence I needed when I adopted my rescue dog. The first aid module alone is worth everything!',
    avatar: 'SK',
    cert: 'Professional Dog Care',
  },
  {
    name: 'Marcus L.',
    role: 'Cat parent of 3',
    text: 'I thought I knew everything about cats after 10 years. The Expert level completely changed how I manage my multi-cat household.',
    avatar: 'ML',
    cert: 'Expert Multi-Pet',
  },
  {
    name: 'Priya M.',
    role: 'Bird enthusiast',
    text: 'The bird care course is so detailed and practical. My vet actually commented on how well-informed I was!',
    avatar: 'PM',
    cert: 'Standard Bird Care',
  },
]

export const STATS = [
  { label: 'Pet Owners Certified', value: '12,400+' },
  { label: 'Courses Available', value: '48' },
  { label: 'Pet Types Covered', value: '6' },
  { label: 'Average Rating', value: '4.8★' },
]
